### ISSUE TITLE
Will multiple v1-bot servers compete to match same limit orders?

### ISSUE THREAD

**Issue by ashuralyk** [ickb/stack#5]
multiple match servers see the same vision in a same chain, so they are competing to match the same iCKB limit orders, is that true?

**Comment by phroi** [comment]
Hey @ashuralyk, thank you for publicly expressing your interest in iCKB as part of the integration of iCKB in NervDAO, I personally appreciate a lot!! 🙏

Yes, bots are competing with each other for on-chain state. I'm also randomizing the wait times between two executions.


Love & Peace, Phroi

**Comment by phroi** [comment]
Closing this for now, feel free to reopen the issue 🤗
